### ISSUE TITLE
Using only https sites

### ISSUE THREAD

**Issue by sapeol** [neeravnadla/pixelbay#4]
Need to either remove http only websites or alteast let the user know in the title it's not https

**Comment by sapeol** [comment]
![image](https://user-images.githubusercontent.com/32122779/151132288-afc3f76f-8b7c-461d-8e7c-dbb47991039d.png)
Sites like these

**Comment by neeravnadla** [comment]
hey, thanks for raising the issue. we will look into it asap. 
also, there's already an open issue for these kinds of suggestions. 
-- [here](https://github.com/neeravnadla/pixelbay/issues/1) --
