### ISSUE TITLE
Colors attract Eyes

### ISSUE THREAD

**Issue by omegaui** [neeravnadla/pixelbay#5]
@neeravnadla 

I think it would be cool if every pixel represents an art or is of different gradient colors.

**Comment by neeravnadla** [comment]
yeah, I'm aware of the color selection (currently color randomly generated) is not so great right now. 
initially, I try to put an icon (favicon) of the website on the respective pixel but it didn't work out well.

maybe in the future, I replace it with pixel art.

or someone else improve U do itI.

**Comment by omegaui** [comment]
A Pixel Art would be a good one!
